version: '3.9'
services:
  redis:
    image: 'redis'
    container_name: redis
    ports:
      - '6379:6379'
  app:
    container_name: authApp
    build: ./server
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    links:
      - redis
    depends_on:
      - redis